name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: "0 9 * * 1"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-python-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Update Python dependencies
        run: |
          uv sync --upgrade

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet uv.lock; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update Python dependencies"
          title: "chore: Update Python dependencies"
          body: |
            Automated dependency update by GitHub Actions.

            This PR updates Python dependencies to their latest compatible versions.

            Please review the changes and ensure all tests pass before merging.
          branch: automated/update-python-deps
          delete-branch: true

  update-frontend-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web_ui/package-lock.json

      - name: Update frontend dependencies
        working-directory: web_ui
        run: |
          npm update
          npm audit fix --audit-level moderate

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet web_ui/package.json web_ui/package-lock.json; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update frontend dependencies"
          title: "chore: Update frontend dependencies"
          body: |
            Automated dependency update by GitHub Actions.

            This PR updates frontend (Node.js) dependencies to their latest compatible versions.

            Please review the changes and ensure all tests pass before merging.
          branch: automated/update-frontend-deps
          delete-branch: true
